spring.application.name=certificadosDRSU

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=local


# Estructurar archivo "application-local.properties" así:

# spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:{DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
